// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQkSjiVCRQcyoIoMacTo-k_qxp95M9-kU',
    appId: '1:144915721417:web:49395301c6114a0de3f118',
    messagingSenderId: '144915721417',
    projectId: 'user-af8d9',
    authDomain: 'user-af8d9.firebaseapp.com',
    storageBucket: 'user-af8d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6KHdplv2GScz89YegvW_fKvhpfBjLqc',
    appId: '1:144915721417:android:d31debad2c40917ee3f118',
    messagingSenderId: '144915721417',
    projectId: 'user-af8d9',
    storageBucket: 'user-af8d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx2wCqhxQGH_8hGSD3gd1XAUNNAFGDhbU',
    appId: '1:144915721417:ios:736b336c84a535fae3f118',
    messagingSenderId: '144915721417',
    projectId: 'user-af8d9',
    storageBucket: 'user-af8d9.appspot.com',
    iosBundleId: 'com.example.crudUserFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx2wCqhxQGH_8hGSD3gd1XAUNNAFGDhbU',
    appId: '1:144915721417:ios:736b336c84a535fae3f118',
    messagingSenderId: '144915721417',
    projectId: 'user-af8d9',
    storageBucket: 'user-af8d9.appspot.com',
    iosBundleId: 'com.example.crudUserFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQkSjiVCRQcyoIoMacTo-k_qxp95M9-kU',
    appId: '1:144915721417:web:0648862bf8205e61e3f118',
    messagingSenderId: '144915721417',
    projectId: 'user-af8d9',
    authDomain: 'user-af8d9.firebaseapp.com',
    storageBucket: 'user-af8d9.appspot.com',
  );
}
